name: Update distribution files for Github Pages
run-name: Generate & push distribution files to gh-pages branch

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    env:
      working-directory: blog
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.15.0]
        pnpm: [6.1]

    runs-on: ${{ matrix.os }}
    permissions: 
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}

      - name: Install Node
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node }}
      
      - name: Install all dependencies with pnpm
        run: pnpm install
        working-directory: ${{env.working-directory}}
      
      - name: Invoke Nuxt Static Site Generation
        run: pnpm run generate
        working-directory: ${{env.working-directory}}
      
      - name: Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # automatically invoked
          publish_dir: ./${{env.working-directory}}/dist # copy contents from this folder to gh-pages branch

      
          
      

      
          