name: Build & Deploy to Github Pages
run-name: ${{ github.actor }} is building & deploying to Github Pages

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    env:
      working-directory: blog
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.15.0]
        pnpm: [6.1]

    runs-on: ${{ matrix.os }}
    permissions: 
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}
        id: pnpm-install

      - name: Install Node
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      
      - name: Install all dependencies with pnpm
        run: pnpm install
        working-directory: ${{env.working-directory}}
      
      - name: Invoke Nuxt Static Site Generation
        run: pnpm run generate
        working-directory: ${{env.working-directory}}
      
      - name: Deploy # Pushes the files to a branch called "gh-pages" that will be used as deployment branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # automatically invoked
          publish_dir: ./${{env.working-directory}}/dist # Nuxt export the statically generated files in the dist directory by default

      
          
      

      
          